// This file was autogenerated by:
// "./create_font_headers.py ../Bravura/otf/Bravura.otf ../Bravura/bravura_metadata.json bravura"
//

namespace bravura
{
    juce::Typeface::Ptr createTypeface();

} // namespace bravura
