// This file was autogenerated by:
// "./create_font_headers.py ../Petaluma/redist/otf/Petaluma.otf ../Petaluma/redist/petaluma_metadata.json petaluma"
//

namespace petaluma
{
    juce::Typeface::Ptr createTypeface();

} // namespace petaluma
